
% : %.hs
	ghc --make $@

PROGS := \
  copy \
  find \
  fixeols \
  jsonMain \
  pgm \
  readDouble \
  sumInternetUsage \
  tempFileFun \
  toUpperBanner \
  toupper \

all: ${PROGS}
clean:
	rm -f ${PROGS}
