ColourPrefs
  { keyword = [ Foreground Green , Underscore ]
  , keyglyph = [ Foreground Red ]
  , layout = [ Foreground Cyan ]
  , comment = [ Foreground Blue , Italic ]
  , conid = [ Normal ]
  , varid = [ Normal ]
  , conop = [ Foreground Red , Bold ]
  , varop = [ Foreground Cyan ]
  , string = [ Foreground Magenta ]
  , char = [ Foreground Magenta ]
  , number = [ Foreground Magenta ]
  , cpp = [ Foreground Magenta , Dim ]
  , selection = [ Bold , Foreground Magenta ]
  , variantselection = [ Dim , Foreground Red , Underscore ]
  , definition = [ Foreground Blue ]
  }
