#!/bin/bash

program=$0
baseProgram=$(basename $0)
which=$1
myDir="$HOME/.podcaster"
downloadDir=$myDir/Downloads
enclosuresFile=$myDir/enclosures.txt
enclosureLimit=15

if [[ $which == 'update' ]]; then
  $program check && $program download
elif [[ $which == "check" ]]; then
  cat $myDir/podcaster.cfg | while read feedUrl; do
    echo "Checking feed ${feedUrl}"
    feedFile=$(tempfile)
    wget -qc "$feedUrl" -O ${feedFile}
    Xtract -n "//rss/channel/item/enclosure/@url" ${feedFile} | head -${enclosureLimit} >>${enclosuresFile}
    rm -f ${feedFile}
    sort -uo ${enclosuresFile} ${enclosuresFile}
  done
elif [[ $which == "download" ]]; then
  mkdir -p $downloadDir
  cd $downloadDir
  exec wget -ci $myDir/enclosures.txt
else
  cat <<! >&2
Usage: ${baseProgram} update|check|download

  update   - check feeds and download
  check    - check feeds only
  download - download only
!
  exit 2
fi
