#!/bin/bash

for rent in 200 250 300 350 400 450 500 550 600 650 700 750 800; do
  reportFile="reports/dcf-house-price-value-using-${rent}-per-week-rent.txt"
  echo "Generated report ${reportFile}..."
  (
     echo "Rate   Price       Weekly x  Annual x"
     echo "~~~~   ~~~~~       ~~~~~~~~  ~~~~~~~~"
     echo ""
    ./DiscountedCashFlow ${rent} 0.0 20.0 
  ) >$reportFile
done
