
% : %.hs
	ghc --make $@

PROGS := \
  catGirlfriend \
  colours \
  copyFile \
  echo \
  foreverYoung \
  helloFirstLast \
  hello \
  helloYou \
  newtypeVerseDataLaziness \
  palindromes \
  p \
  reverseLoop \
  shortLines \
  todo \
  upcase \
  upGirlfriend \


all: ${PROGS}
clean:
	rm ${PROGS}
