name: nix-derivation-parser

dependencies:
  - attoparsec
  - base
  - containers
  - criterion
  - deepseq
  - optparse-generic
  - system-filepath
  - text
  - vector

ghc-options: -O2 -Wall -fwarn-tabs

library:
  source-dirs: .

executables:
  query-outputs:
    main: query-outputs.hs

benchmarks:
  bench1:
    main: bench.hs
