name: nix-derivation-parser

ghc-options: -O2 -Wall -fwarn-tabs

dependencies:
  - attoparsec
  - base
  - bytestring
  - containers
  - deepseq
  - system-filepath
  - text
  - vector

library:
  source-dirs: src

executables:
  query-outputs:
    main: query-outputs.hs
    dependencies:
      - nix-derivation-parser
      - optparse-generic

benchmarks:
  bench1:
    main: bench.hs
    dependencies:
      - criterion
      - nix-derivation-parser
