name: non-closeable-channels

ghc-options: -Wall -fwarn-tabs

executables:
  closeable-channels-stm:
    main: closeable-channels-stm.hs
    dependencies:
      - async
      - base
      - bytestring
      - stm
      - text
